"""Added question_code and created_at columns

Revision ID: d9476bfdd09b
Revises: 200e6381bfde
Create Date: 2025-03-30 19:32:24.841877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9476bfdd09b'
down_revision: Union[str, None] = '200e6381bfde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_code', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'question_code')
    # ### end Alembic commands ###
