name: Deploy to Production

on:
  push:
    branches: [release]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment archive
        run: tar --warning=no-file-changed -czf deployment.tar.gz --exclude=".git" --exclude=".github" .

      - name: Transfer to production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deployment.tar.gz"
          target: "/tmp"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit if any command fails
            
            echo "🔹 Ensuring deployment directory exists..."
            mkdir -p /CodeCraft

            echo "🔹 Removing old deployment files..."
            rm -rf /CodeCraft/*

            echo "🔹 Extracting new deployment files..."
            tar -xzf /tmp/deployment.tar.gz -C /CodeCraft

            echo "🔹 Creating .env file..."
            cat <<EOF > /CodeCraft/.env
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
            COMPILER_API_ENDPOINT=${{ secrets.COMPILER_API_ENDPOINT }}
            CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}
            EOF
            echo "✅ .env file created."

            echo "🔹 Checking if Docker is installed..."
            if ! command -v docker &> /dev/null; then
              echo "❌ Docker is not installed! Exiting..."
              exit 1
            fi

            echo "🔹 Checking if Docker Compose is installed..."
            if ! command -v docker-compose &> /dev/null; then
              echo "❌ Docker Compose is not installed! Exiting..."
              exit 1
            fi

            echo "🔹 Starting Docker Compose services..."
            cd /CodeCraft
            export COMPOSE_PROJECT_NAME=codecraft
            docker-compose up -d --build --force-recreate

            echo "🔹 Verifying deployment success..."
            RUNNING_CONTAINERS=$(docker-compose ps --services --filter "status=running" | wc -l)
            EXPECTED_CONTAINERS=$(docker-compose ps --services | wc -l)

            if [ "$RUNNING_CONTAINERS" -eq "$EXPECTED_CONTAINERS" ]; then
                echo "✅ Deployment successful! All containers are running."
                exit 0
            else
                echo "❌ Deployment failed! Only $RUNNING_CONTAINERS out of $EXPECTED_CONTAINERS containers are running."
                exit 1
            fi
